// Docs on event and context https://www.netlify.com/docs/functions/#the-handler-method
import  GoogleSpreadsheet  from 'google-spreadsheet';

const handler = async (event) => {
    try {
      const subject = event.queryStringParameters.name || 'testSheet'
      const doc = new GoogleSpreadsheet();
      await doc.useServiceAccountAuth({
        // env var values are copied from service account credentials generated by google
        // see "Authentication" section in docs for more info
        client_email: process.env.EMAIL_SERVICE_GOOGLE,
        private_key: process.env.KEY_SERVICE_GOOGLE,
      });
      await doc.createNewSpreadsheetDocument({ title: 'This is a new doc' });
      return {
        statusCode: 200,
        body: JSON.stringify({ message: `Hello ${subject}` , sheetId: doc.spreadsheetId}),
        // // more keys you can return:
        // headers: { "headerName": "headerValue", ... },
        // isBase64Encoded: true,
      }
    } catch (error) {
      return { statusCode: 500, body: error.toString() }
    }
  }
  
  module.exports = { handler }