---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: src/data/sections
  label: sections
  create: documents
  match: "**/*"
  new_doc_ext: json
  templates:
  - section
- type: directory
  path: src/data/professeurs
  label: professeurs
  create: documents
  match: "**/*"
  new_doc_ext: json
  templates:
  - professeur
upload_dir: public/img/uploads
public_path: img/uploads
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
